// const products = [
// {
// id: 1,
// title: "Arroz integral",
// description: "Arroz integral yamani",
// category: "Almacen",
// filtradito: "oferta",
// price: 150,
// qty: 0,
// image: 'ARROZ.jpg',
// image2: 'ARROZ.jpg',
// image3: 'ARROZ.jpg',
// stock: 8
// },
// {
// id: 2,
// title: "Yerba",
// description: "Yerba porongo",
// category: "Almacen",
// filtradito: "oferta",
// price: 1200,
// qty: 0,
// image: 'YERBA.jpg',
// image2: 'YERBA.jpg',
// image3: 'YERBA.jpg',
// stock: 12
// },
// {
// id: 3,
// title: "Choclo",
// description: "Choclo congelado",
// category: "Congelados",
// filtradito: "oferta",
// price: 460,
// qty: 0,
// image: 'CHOCLO.jpg',
// image2: 'CHOCLO2.jpg',
// image3: 'CHOCLO3.jpg',
// stock: 44
// },
// {
// id: 4,
// title: "Fideos",
// description: "Fideos de masa integral",
// category: "Almacen",
// filtradito: "oferta",
// price: 421,
// qty: 0,
// image: 'FIDEOS.jpg',
// image2: 'FIDEOS.jpg',
// image3: 'FIDEOS.jpg',
// stock: 54
// },
// {
// id: 5,
// title: "Mayonesa",
// description: "Mayonesa light",
// category: "Almacen",
// filtradito: "oferta",
// price: 560,
// qty: 0,
// image: 'MAYONESA.jpg',
// image2: 'MAYONESA.jpg',
// image3: 'MAYONESA.jpg',
// stock: 33
// },
// {
// id: 6,
// title: "Hamburguesas Pollo",
// description: "Hamburguesas de Pollo congueladas",
// category: "Congelados",
// filtradito: "oferta",
// price: 1530,
// qty: 0,
// image: 'HAMBURGESA DE POLLO.jpg',
// image2: 'HAMBURGESA DE POLLO.jpg',
// image3: 'HAMBURGESA DE POLLO.jpg',
// stock: 33
// },
// {
// id: 7,
// title: "Galletas de agua",
// description: "Crackers galletas de agua",
// category: "Almacen",
// filtradito: "oferta",
// price: 220,
// qty: 0,
// image: 'GALLETAS DE AGUA.jpg',
// image2: 'GALLETAS DE AGUA.jpg',
// image3: 'GALLETAS DE AGUA.jpg',
// stock: 33
// },
// {
// id: 8,
// title: "Galletas de Garbanzo",
// description: "Galletas de harina de garbanzo",
// category: "Almacen",
// filtradito: "oferta",
// price: 400,
// qty: 0,
// image: 'GALLETAS DE GARBANZO.jpg',
// image2: 'GALLETAS DE GARBANZ.jpg',
// image3: 'GALLETAS DE GARBANZ.jpg',
// stock: 33
// },{
// id: 9,
// title: "Sal Rosa",
// description: "Sal del himalaya rosa",
// category: "Almacen",
// filtradito: "oferta",
// price: 560,
// qty: 0,
// image: 'SAL ROSA.jpg',
// image2: 'SAL ROSA.jpg',
// image3: 'SAL ROSA.jpg',
// stock: 33
// },{
// id: 10,
// title: "Alfajor",
// description: "Alfajor de chocolate",
// category: "Dulces",
// filtradito: "oferta",
// price: 160,
// qty: 0,
// image: 'ALFAJOR.jpg',
// image2: 'ALFAJOR.jpg',
// image3: 'ALFAJOR.jpg',
// stock: 14
// },{
// id: 11,
// title: "Jugo Manzana",
// description: "Jugo de Manzana",
// category: "Frescos",
// filtradito: "oferta",
// price: 560,
// qty: 0,
// image: 'JUGO1.jpg',
// image2: 'JUGO1.jpg',
// image3: 'JUGO1.jpg',
// stock: 27
// },{
// id: 12,
// title: "Jugo Frutilla",
// description: "Jugo de frutilla",
// category: "Frescos",
// filtradito: "oferta",
// price: 560,
// qty: 0,
// image: 'JUGO2.jpg',
// image2: 'JUGO2.jpg',
// image3: 'JUGO2.jpg',
// stock: 30
// }  
// ]

// export default products
